//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TypisheApi.Localizations {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TypisheApi.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BPM.
        /// </summary>
        public static string BumpsPerMinute {
            get {
                return ResourceManager.GetString("BumpsPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPM.
        /// </summary>
        public static string CharactersPerMinute {
            get {
                return ResourceManager.GetString("CharactersPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CPS.
        /// </summary>
        public static string CharactersPerSecond {
            get {
                return ResourceManager.GetString("CharactersPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom visual brush (XAML-code).
        /// </summary>
        public static string CustomVisualBrush {
            get {
                return ResourceManager.GetString("CustomVisualBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit the exercise.
        /// </summary>
        public static string EditTheExercise {
            get {
                return ResourceManager.GetString("EditTheExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable auto restart after fail.
        /// </summary>
        public static string EnableAutoRestartAfterFail {
            get {
                return ResourceManager.GetString("EnableAutoRestartAfterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enable the Hardcore Mode.
        /// </summary>
        public static string EnableHardcoreMode {
            get {
                return ResourceManager.GetString("EnableHardcoreMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Font size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Font weight.
        /// </summary>
        public static string FontWeight {
            get {
                return ResourceManager.GetString("FontWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 900, Black.
        /// </summary>
        public static string FwBlack {
            get {
                return ResourceManager.GetString("FwBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 700, Bold.
        /// </summary>
        public static string FwBold {
            get {
                return ResourceManager.GetString("FwBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 800, Extra bold.
        /// </summary>
        public static string FwExtraBold {
            get {
                return ResourceManager.GetString("FwExtraBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 200, Extra light.
        /// </summary>
        public static string FwExtraLight {
            get {
                return ResourceManager.GetString("FwExtraLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 300, Light.
        /// </summary>
        public static string FwLight {
            get {
                return ResourceManager.GetString("FwLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 500, Medium.
        /// </summary>
        public static string FwMedium {
            get {
                return ResourceManager.GetString("FwMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 400, Regular.
        /// </summary>
        public static string FwRegular {
            get {
                return ResourceManager.GetString("FwRegular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 600, Semi-bold.
        /// </summary>
        public static string FwSemiBold {
            get {
                return ResourceManager.GetString("FwSemiBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 100, Thin.
        /// </summary>
        public static string FwThin {
            get {
                return ResourceManager.GetString("FwThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 999, Ultra black.
        /// </summary>
        public static string FwUltraBlack {
            get {
                return ResourceManager.GetString("FwUltraBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 001, Ultra thin.
        /// </summary>
        public static string FwUltraThin {
            get {
                return ResourceManager.GetString("FwUltraThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ImageBrush.
        /// </summary>
        public static string ImageBrush {
            get {
                return ResourceManager.GetString("ImageBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image size.
        /// </summary>
        public static string ImageSize {
            get {
                return ResourceManager.GetString("ImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SC RGB.
        /// </summary>
        public static string ImScRgb {
            get {
                return ResourceManager.GetString("ImScRgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SRGB.
        /// </summary>
        public static string ImSRgb {
            get {
                return ResourceManager.GetString("ImSRgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interpolation mode.
        /// </summary>
        public static string InterpolationMode {
            get {
                return ResourceManager.GetString("InterpolationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Linear gradient brush.
        /// </summary>
        public static string LinearGradientBrush {
            get {
                return ResourceManager.GetString("LinearGradientBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load next exercise.
        /// </summary>
        public static string LoadNextExercise {
            get {
                return ResourceManager.GetString("LoadNextExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load previous exercise.
        /// </summary>
        public static string LoadPreviousExercise {
            get {
                return ResourceManager.GetString("LoadPreviousExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Load random exercise.
        /// </summary>
        public static string LoadRandomExercise {
            get {
                return ResourceManager.GetString("LoadRandomExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Radial gradient brush.
        /// </summary>
        public static string RadialGradientBrush {
            get {
                return ResourceManager.GetString("RadialGradientBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reload the exercise.
        /// </summary>
        public static string ReloadExercise {
            get {
                return ResourceManager.GetString("ReloadExercise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на See the lesson statistics.
        /// </summary>
        public static string SeeStatistics {
            get {
                return ResourceManager.GetString("SeeStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show in the file explorer.
        /// </summary>
        public static string ShowInFileExplorer {
            get {
                return ResourceManager.GetString("ShowInFileExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pad.
        /// </summary>
        public static string SmPad {
            get {
                return ResourceManager.GetString("SmPad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reflect.
        /// </summary>
        public static string SmReflect {
            get {
                return ResourceManager.GetString("SmReflect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repeat.
        /// </summary>
        public static string SmRepeat {
            get {
                return ResourceManager.GetString("SmRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Solid color brush.
        /// </summary>
        public static string SolidColorBrush {
            get {
                return ResourceManager.GetString("SolidColorBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Spread method.
        /// </summary>
        public static string SpreadMethod {
            get {
                return ResourceManager.GetString("SpreadMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start perfect demonstration mode.
        /// </summary>
        public static string StartDemonstrationMode {
            get {
                return ResourceManager.GetString("StartDemonstrationMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill.
        /// </summary>
        public static string StFill {
            get {
                return ResourceManager.GetString("StFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        public static string StNone {
            get {
                return ResourceManager.GetString("StNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stretch.
        /// </summary>
        public static string Stretch {
            get {
                return ResourceManager.GetString("Stretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uniform.
        /// </summary>
        public static string StUniform {
            get {
                return ResourceManager.GetString("StUniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Uniform to fill.
        /// </summary>
        public static string StUniformToFill {
            get {
                return ResourceManager.GetString("StUniformToFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Base line.
        /// </summary>
        public static string TdBaseLine {
            get {
                return ResourceManager.GetString("TdBaseLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        public static string TdNone {
            get {
                return ResourceManager.GetString("TdNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Over line.
        /// </summary>
        public static string TdOverLine {
            get {
                return ResourceManager.GetString("TdOverLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Strike through.
        /// </summary>
        public static string TdStrikeThrough {
            get {
                return ResourceManager.GetString("TdStrikeThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Under line.
        /// </summary>
        public static string TdUnderLine {
            get {
                return ResourceManager.GetString("TdUnderLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text decorations.
        /// </summary>
        public static string TextDecorations {
            get {
                return ResourceManager.GetString("TextDecorations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tile mode.
        /// </summary>
        public static string TileMode {
            get {
                return ResourceManager.GetString("TileMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flip by X-axis.
        /// </summary>
        public static string TmFlipX {
            get {
                return ResourceManager.GetString("TmFlipX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flip by X &amp; Y axises.
        /// </summary>
        public static string TmFlipXY {
            get {
                return ResourceManager.GetString("TmFlipXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Flip by Y-axis.
        /// </summary>
        public static string TmFlipY {
            get {
                return ResourceManager.GetString("TmFlipY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        public static string TmNone {
            get {
                return ResourceManager.GetString("TmNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tile.
        /// </summary>
        public static string TmTile {
            get {
                return ResourceManager.GetString("TmTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WPM.
        /// </summary>
        public static string WordsPerMinute {
            get {
                return ResourceManager.GetString("WordsPerMinute", resourceCulture);
            }
        }
    }
}
